spring.application.name=login-sistema-frete

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# secret deve ter no minimo 32 caracteres para HMAC-SHA256
jwt.secret=aG7!s9Dk2@pL9qR5zX1vB8nN3mM6jK4hL
# expiracao em milissegundos: 86400000 = 24 horas
jwt.expiration=86400000

server.port=8080